[theme]

primaryColor="#c61b6e"
backgroundColor="#330066"
secondaryBackgroundColor="#440077"
textColor="#ffffff"
font="sans sarif"

#[theme]
#
#primaryColor="#d33682"
#backgroundColor="#002b36"
#secondaryBackgroundColor="#586e75"
#textColor="#fafafa"
#font="sans serif"

